version: '3'
services:
  zap:
    build:
      context: .
      dockerfile: Dockerfile.zap
    ports:
      - "8080:8080"
    environment:
      - ZAP_API_KEY=${ZAP_API_KEY}

  nikto:
    build:
      context: .
      dockerfile: Dockerfile.nikto
    volumes:
      - ./nikto-reports:/nikto/reports

  nessus:
    build:
      context: .
      dockerfile: Dockerfile.nessus
    ports:
      - "8834:8834"
    environment:
      - NESSUS_ADMIN_USERNAME=${NESSUS_ADMIN_USERNAME}
      - NESSUS_ADMIN_PASSWORD=${NESSUS_ADMIN_PASSWORD}
      - NESSUS_LICENSE_CODE=${NESSUS_LICENSE_CODE}

volumes:
  nikto-reports:
